### PR TITLE
folder structure update

### PR DESCRIPTION
**Pull request by thoschuller**
folder structure update
* adjusted to new folder structure for journeymap
* changed README.md to reflect folder change
* upgraded version number according to semVer (breaking API change)

### CODE REVIEW

**Comment by Entropy5** [comment]
This fixes the converter for new minecraft versions, but I think 1.12 journeymap still uses the old structure
i might just keep this as a branch and provide a jar from this branch for new versions

**Comment by thoschuller** [comment]
Good call! I'll see if I have time to write a mix between the two soon, so it'll detect the folder structure and change its internal workings automatically

**Comment by Entropy5** [comment]
yea it should be as simple as just checking which of the folder names exist
https://github.com/Entropy5/JMtoXaero/issues/8

**Comment by thoschuller** [comment]
It now includes a check on the existing folder name structure, and because of the backwards-compatible input a major version increment is no longer necessary

**Comment by Entropy5** [comment]
just running one more test and then ill upload release

**Pull request merged**
